config/routes.rb
Rails.application.routes.draw do
  get "posts/index"
  devise_for :users

  root "posts#index"

  resources :posts, only: [ :index, :new, :create, :destroy  ]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts

  validates :username, presence: true, uniqueness: true, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, uniqueness: true
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :username ])
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]

  def index
    @post = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path, success: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
      flash.now[:error] = "An error occured!"
    end
  end

  private

  def post_params
    params.expect(post: [ :title, :content ])
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [ :new, :create ]

  def index
    @post = Post.order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path, success: "Post was successfully created."
    else
      render :new, status: :unprocessable_entity
      flash.now[:error] = "An error occured!"
    end
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user == current_user
      @post.destroy
      redirect_to posts_path, notice: "Post was successfully deleted."
    else
      redirect_to posts_path, alert: "You are not authorized to delete this post."
    end
  end

  private

  def post_params
    params.expect(post: [ :title, :content ])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Members Only" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class=header-bar>

  <h1>Welcome to the Clubhouse</h1>

  <div class="header-button-container">

    <%= button_to "Create Post", new_post_path, method: :get, class: "header-button" %>

    <% if user_signed_in? %>
      <%= button_to "Log out",
      destroy_user_session_path,
      method: "delete", class: "header-button",
      data: {
        turbo: "false",
      } %>
    <% else %>
      <%= button_to "Log in", new_user_session_path, method: :get, class: "header-button" %>
    <% end %>

  </div>

</div>

<div class="posts-wrapper">

  <% @post.all.each do |post| %>

    <div class="post-card">

      <article>
        <h3><%= post.title %></h3>
        <p class="card-description"><%= post.content %></p>
      </article>

      <h4 class="post-author">
        <%= user_signed_in? ? post.user.email : "Anonymous" %>
      </h4>

      <% if user_signed_in? && current_user == post.user %>
        <%= button_to "Delete", post_path(post), method: :delete, data: { turbo: false, confirm: "Are you sure?" }, class: "btn delete-btn" %>
      <% end %>

    </div>

  <% end %>

</div>

app/views/posts/new.html.erb
<div class="header-bar">
  <h1>New Post</h1>

  <div class="header-button-container">
    <%= button_to "Back to Posts", posts_path, method: :get, class: "header-button" %>
    <% if user_signed_in? %>
      <%= button_to "Log out", destroy_user_session_path, method: :delete, class: "header-button", data: { turbo: "false" } %>
    <% else %>
      <%= button_to "Log in", new_user_session_path, method: :get, class: "header-button" %>
    <% end %>
  </div>
</div>

<div class="new-post-card">
  <%= form_with(model: @post, local: true) do |form| %>
    <div>
      <%= form.label :title %><br>
      <%= form.text_field :title, class: "form-control" %>
    </div>

    <div>
      <%= form.label :content %><br>
      <%= form.text_area :content, class: "textarea-large" %>
    </div>

    <div>
      <%= form.submit "Create Post", class: "btn btn-primary" %>
    </div>
  <% end %>
</div>